import{onAuthStateChanged,auth,db,doc,getDoc,signOut,forceOffline,hasBluekidPlus,FirebaseHelper}from"./util/firebase.js";import{isUserVaild,UserReasons}from"./util/auth_helper.js";import{CommunityUtilites}from"./profile/community.js";async function checkVaild(i,d){return new Promise(async(e,n)=>{var t=isUserVaild(i,d);if(t.reason==UserReasons.OVERDUE)location.href="../auth/overdue.html";else if(t.reason==UserReasons.BANNED)(o=document.createElement("dialog")).innerHTML=`
            <h1>You're banned.</h1>
            <p>Reason: ${t.banReason}</p>
            <br>
            <b>You can resolve this by contacting the developer.</b>
            <button class="puffy_button danger" id="logout__ban">Logout</button>
        `,document.body.append(o),o.showModal(),document.getElementById("logout__ban").addEventListener("click",async()=>{await signOut(auth),location.href="../index.html"});else if(t.reason==UserReasons.TEMPBANNED){var o=document.createElement("dialog"),a=1e3*t.endsOn.seconds,a=new Date(a).getTime();let e=Math.floor((a-Date.now())/864e5),n="days";console.log(e),0==e&&(e=Math.floor((a-Date.now())/36e5),n="hours",0==e)&&(e=Math.floor((a-Date.now())/6e4),n="minutes"),o.innerHTML=`
            <h1>You're banned.</h1>
            <p>Reason: ${t.banReason}</p>
            <p>Ends in ${e} ${n}.</p>
            <br>
            <b>You can resolve this sooner by contacting the developer.</b>
            <button class="puffy_button danger" id="logout__ban">Logout</button>
        `,document.body.append(o),o.showModal(),void document.getElementById("logout__ban").addEventListener("click",async()=>{await signOut(auth),location.href="../index.html"})}else t.reason!=UserReasons.EMAIL_NOT_VERIFIED&&document.getElementById("notemailverified").remove(),t.reason==UserReasons.OTHER&&showNotification(3,"Something went wrong checking user info. Continuing as normal."),e()})}var cachedBadges=null;async function loadBadges(e){var n=await FirebaseHelper.getBadges(e);for(let e=0;e<n.length;e++){var t=n[e],o=document.getElementById("badgeex").cloneNode(!0),t=(o.id="",(o.title=t).replace(" ",""));o.children[0].src=`../asset/badges/${t}.png`,"BluekidPlus"==t&&o.classList.add("badge--bkp"),document.getElementById("badges").appendChild(o)}}onAuthStateChanged(auth,async e=>{if(e){var n=e.uid,t=doc(db,"users",n),t=await getDoc(t).then(e=>e.exists()?e.data():"UNKNOWN"),n=(loadBadges(n),await checkVaild(e,t),document.getElementById("username").innerText=t.username,null!=t.friends&&(document.getElementById("friends").innerHTML=t.friends.length),Date.parse(t.creation)-new Date),e=-Math.floor(n/864e5),o=(document.getElementById("accountAge").innerHTML=e,document.getElementById("accountAge").title=t.creation.toLocaleString(),document.getElementById("tokens").innerHTML=t.tokens.toLocaleString(),2==t.version?document.getElementById("datav2").remove():document.getElementById("datav2Popup").showModal(),await CommunityUtilites.getAllRequests(auth.currentUser));console.log(o);for(let e=0;e<o.length;e++){let n=o[e];var a=await getDoc(doc(db,"users",n));if(null!=!a.data()){document.getElementById("noincomingfriends").style.display="none;";let e=document.getElementById("requestex").cloneNode(!0);e.id="",e.children[0].children[0].innerText=a.data().username,e.children[0].children[1].innerHTML=n,e.children[1].children[0].addEventListener("click",async()=>{e.children[1].children[0].innerHTML='<i class="fa-solid fa-ellipsis"></i>',e.children[1].children[0].setAttribute("disabled",""),await CommunityUtilites.acceptFriendReq(auth.currentUser,n),location.href="./community.html"}),e.children[1].children[1].addEventListener("click",async()=>{e.children[1].children[1].innerHTML='<i class="fa-solid fa-ellipsis"></i>',e.children[1].children[1].setAttribute("disabled",""),await CommunityUtilites.ignoreFriendReq(auth.currentUser,n),location.href="./community.html"}),document.getElementById("incomingfriendreq").appendChild(e)}}document.getElementById("logout").addEventListener("click",async()=>{await forceOffline(),await signOut(auth),location.href="../index.html"})}else location.href="../auth/login.html"});