import{onAuthStateChanged,auth,db,doc,getDoc,signOut,forceOffline,hasBluekidPlus,FirebaseHelper,insertLoadingScreen,finishLoading,updateLoadingInfo}from"./util/firebase.js";import{isUserVaild,UserReasons}from"./util/auth_helper.js";import{CommunityUtilites}from"./profile/community.js";async function checkVaild(i,s){return new Promise(async(e,n)=>{var t=isUserVaild(i,s);if(t.reason==UserReasons.OVERDUE)location.href="../auth/overdue.html";else if(t.reason==UserReasons.BANNED)(o=document.createElement("dialog")).innerHTML=`
            <h1>You're banned.</h1>
            <p>Reason: ${t.banReason}</p>
            <br>
            <b>You can resolve this by contacting the developer.</b>
            <button class="puffy_button danger" id="logout__ban">Logout</button>
        `,document.body.append(o),o.showModal(),document.getElementById("logout__ban").addEventListener("click",async()=>{await signOut(auth),location.href="../index.html"});else if(t.reason==UserReasons.TEMPBANNED){var o=document.createElement("dialog"),a=1e3*t.endsOn.seconds,a=new Date(a).getTime();let e=Math.floor((a-Date.now())/864e5),n="days";console.log(e),0==e&&(e=Math.floor((a-Date.now())/36e5),n="hours",0==e)&&(e=Math.floor((a-Date.now())/6e4),n="minutes"),o.innerHTML=`
            <h1>You're banned.</h1>
            <p>Reason: ${t.banReason}</p>
            <p>Ends in ${e} ${n}.</p>
            <br>
            <b>You can resolve this sooner by contacting the developer.</b>
            <button class="puffy_button danger" id="logout__ban">Logout</button>
        `,document.body.append(o),o.showModal(),void document.getElementById("logout__ban").addEventListener("click",async()=>{await signOut(auth),location.href="../index.html"})}else t.reason!=UserReasons.EMAIL_NOT_VERIFIED&&document.getElementById("notemailverified").remove(),t.reason==UserReasons.OTHER&&showNotification(3,"Something went wrong checking user info. Continuing as normal."),e()})}var cachedBadges=null;async function loadBadges(i){return new Promise(async(e,n)=>{var t=await FirebaseHelper.getBadges(i);for(let e=0;e<t.length;e++){var o=t[e],a=document.getElementById("badgeex").cloneNode(!0),o=(a.id="",a.dataset.tooltip=o,a.setAttribute("data-tooltip-pos","bottom"),o.replace(" ",""));a.children[0].src=`../asset/badges/${o}.png`,"BluekidPlus"==o&&a.classList.add("badge--bkp"),document.getElementById("badges").appendChild(a)}e()})}onAuthStateChanged(auth,async u=>{if(insertLoadingScreen("content",document.getElementById("content")),u)if(u.isAnonymous)location.href="../auth/login.html";else{let e=u.uid,n=doc(db,"users",e),t=await getDoc(n).then(e=>e.exists()?e.data():"UNKNOWN"),o=(updateLoadingInfo("content","Loading badges [This action can take a bit to warm up]"),await loadBadges(e),await checkVaild(u,t),document.getElementById("username").innerText=t.username,document.getElementById("uid").innerHTML=e,null!=t.friends&&(document.getElementById("friends").innerHTML=t.friends.length),null!=t.profileBlue&&(document.getElementById("pfp").src="../asset/char/"+t.profileBlue),-(Date.parse(t.creation)-new Date)),a=Math.floor(o/1e3),i=Math.floor(o/6e4),s=Math.floor(o/864e5),d=Math.floor(o/36e5),r=Math.floor(o/6048e5),l=Math.floor(o/2628e6),c=Math.floor(o/3154e7);document.getElementById("originalCreation").innerHTML=t.creation,setInterval(()=>{0<c?document.getElementById("accountAge").innerHTML=c+" year"+(1==c?"":"s"):0<l?document.getElementById("accountAge").innerHTML=l+" month"+(1==l?"":"s"):0<r?document.getElementById("accountAge").innerHTML=r+" week"+(1==r?"":"s"):0<s?document.getElementById("accountAge").innerHTML=s+" day"+(1==s?"":"s"):0<d?document.getElementById("accountAge").innerHTML=d+" hour"+(1==d?"":"s"):0<i?document.getElementById("accountAge").innerHTML=i+" minute"+(1==i?"":"s"):0<a&&(document.getElementById("accountAge").innerHTML=a+" second"+(1==a?"":"s"))},250),document.getElementById("coins").innerHTML=t.tokens.toLocaleString(),2==t.version&&document.getElementById("datav2").remove(),updateLoadingInfo("content","Update friend requests");u=await CommunityUtilites.getAllRequests(auth.currentUser);console.log(u),null!=u&&(document.getElementById("newfriendrequests").parentElement.style.display="flex",document.getElementById("newfriendrequests").innerHTML=`${u.length} new friend request${1==u.length?"":"s"}!`),document.getElementById("logout").addEventListener("click",async()=>{await forceOffline(),await signOut(auth),location.href="../index.html"}),finishLoading("content")}else location.href="../auth/login.html"});